[package]
name = "rust"
version = "0.1.0"
edition = "2021"
authors = ["Midka <me@midka.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
surrealdb = "1.0.0-beta.8"
