services:
  postgresql:
    image: postgres
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    user: root
    volumes:
      - ./dev_data/sqldb_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 3s
      retries: 5
  redis:
    image: redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "${REDIS_PASSWORD}"
    user: root
    volumes:
      - ./dev_data/redis:/var/lib/redis/data
    ports:
      - "6379:6739"
  webapi:
    build: ./src/BadWithMoney/
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Postgresql=Host=postgresql;Database=postgres;Username=postgres;Password=${POSTGRES_PASSWORD};Include Error Detail=true
      - ConnectionStrings__Redis=redis,password=${REDIS_PASSWORD}
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started
